# Generated by Django 3.1.12 on 2022-09-17 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_bookborrwed_returnbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookborrwed',
            name='days',
        ),
    ]
