# Generated by Django 4.1.1 on 2022-09-16 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0003_librarian'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Librarian',
            new_name='LibrarianProfile',
        ),
    ]
